import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "@/styles/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import QuestionContextProvider from "@/context/question-context";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={inter.className}>
                <QuestionContextProvider>{children}</QuestionContextProvider>
                {process.env.GA_MEASUREMENT_ID && (
                    <GoogleAnalytics gaId={process.env.GA_MEASUREMENT_ID} />
                )}
            </body>
        </html>
    );
}
